# Generated by Django 5.2.6 on 2026-04-15 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_subscriptions',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subsriber',
            new_name='subscriber',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('subscriber', 'author'), name='unique_subscriptions'),
        ),
    ]
