# Generated by Django 5.2.6 on 2025-10-27 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(help_text='Write a short description about new post! This description will be shown in the main post view!', max_length=500)),
                ('icon', models.TextField(help_text='SVG icon for new category! Write a <svg> HTML tag here...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(help_text='Write a short description about new post! This description will be shown in the main post view!', max_length=500)),
                ('content', models.TextField(help_text='Write a content for your article!')),
                ('image', models.ImageField(blank=True, help_text='Main post image! We recommend use big image in horizontal layout!', upload_to='post_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.category')),
            ],
        ),
    ]
